; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
W1_InitIndex:	.byte $00, (W1_ByRowType_S2 - W1_ByRowType), (W1_ByRowType_S3 - W1_ByRowType), (W1_ByRowType_S4 - W1_ByRowType)
W1_ByRowType:	.byte $20, $24, $21, $23, $23, $21, $23, $43, $43, $43, $43, $44, $43, $63, $62, $6F, $83, $87, $83, $83, $82, $AE, $A3, $A4
W1_ByRowType_S2:
W1_ByRowType_S3:
W1_ByRowType_S4:
W1_ByScrCol:	.byte $01, $02, $04, $06, $08, $0A, $0C, $02, $04, $06, $08, $0A, $0C, $04, $06, $08, $04, $06, $08, $0A, $0C, $04, $06, $08
W1_ByScrCol_S2:
W1_ByScrCol_S3:
W1_ByScrCol_S4:
W1_ObjSets:	.word $1B00, $2F2F, W101O, $2923, $2729, $4949, $4949, $4949, $6969, TLHILLSO, $896E, $8E87, $8989, $A9A3, $A9A9, $29AF, $2929, $2729, $4943, $6949, $6962, $6969, $8989, $8989
W1_ObjSets_S2:
W1_ObjSets_S3:
W1_ObjSets_S4:
W1_LevelLayout:	.word $1B00, $2F2F, W101L, $2923, $2729, $4949, $4949, $4949, $6969, TLHILLSL, $896E, $8E87, $8989, $A9A3, $A9A9, $29AF, $2929, $2729, $4943, $6949, $6962, $6969, $8989, $8989
W1_LevelLayout_S2:
W1_LevelLayout_S3:
W1_LevelLayout_S4:
