; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
W2_InitIndex:	.byte $00, (W2_ByRowType_S2 - W2_ByRowType), (W2_ByRowType_S3 - W2_ByRowType), (W2_ByRowType_S4 - W2_ByRowType)
W2_ByRowType:	.byte $2F, $29, $23, $29, $29, $27, $49, $49, $49, $49, $49, $49, $69, $69, $69, $69, $6E, $89, $87, $8E, $89, $89, $A3, $A9, $A9, $A9, $AF
W2_ByRowType_S2:	.byte $29, $29, $29, $29, $27, $43, $49, $49, $69, $62, $69, $69, $69, $89, $89, $89, $89, $A9, $A9, $A9
W2_ByRowType_S3:
W2_ByRowType_S4:
W2_ByScrCol:	.byte $04, $06, $08, $0A, $0C, $0E, $04, $06, $08, $0A, $0C, $0E, $04, $08, $0A, $0C, $0E, $04, $06, $08, $0C, $0E, $02, $04, $06, $08, $0E
W2_ByScrCol_S2:	.byte $10, $12, $14, $16, $18, $10, $14, $18, $10, $12, $14, $18, $1A, $10, $12, $14, $1A, $10, $12, $14
W2_ByScrCol_S3:
W2_ByScrCol_S4:
W2_ObjSets:
W2_ObjSets_S2:
W2_ObjSets_S3:
W2_ObjSets_S4:
W2_LevelLayout:
W2_LevelLayout_S2:
W2_LevelLayout_S3:
W2_LevelLayout_S4:
