; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W101L	; Alternate level layout
	.word W101O	; Alternate object layout
	.byte LEVEL1_SIZE_02 | LEVEL1_YSTART_140
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKLOW | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $1A, $00, $C0, $1F, $40, $0F, $09, $13, $04, $E2, $14, $08, $E2, $E0, $51, $C6
	.byte $38, $01, $91, $FF