; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W101AL	; Alternate level layout
	.word W101AO	; Alternate object layout
	.byte LEVEL1_SIZE_09 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_FREE | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $19, $00, $C1, $19, $36, $03, $24, $36, $05, $00, $16, $0F, $45, $75, $11, $21
	.byte $33, $10, $83, $36, $1A, $80, $35, $1B, $82, $36, $1E, $80, $18, $0A, $91, $12
	.byte $02, $E2, $19, $1F, $C1, $17, $18, $26, $92, $18, $31, $91, $36, $28, $82, $36
	.byte $29, $00, $73, $29, $20, $1A, $37, $C0, $4B, $17, $43, $36, $1A, $4B, $A4, $14
	.byte $3E, $64, $31, $3F, $81, $11, $45, $86, $2E, $47, $81, $0E, $4D, $75, $2B, $4E
	.byte $82, $6B, $4F, $20, $16, $3A, $E2, $0E, $43, $E2, $11, $51, $E2, $19, $3D, $92
	.byte $19, $52, $92, $37, $57, $A2, $76, $57, $21, $1A, $5D, $A6, $1A, $7A, $A4, $1A
	.byte $71, $A5, $37, $77, $82, $37, $7F, $82, $77, $78, $20, $77, $80, $20, $34, $6C
	.byte $95, $37, $68, $A2, $32, $6C, $81, $15, $60, $E3, $14, $70, $E3, $36, $6E, $0E
	.byte $2D, $55, $80, $31, $55, $80, $33, $55, $80, $2F, $55, $80, $2C, $54, $80, $E0
	.byte $61, $10, $E6, $71, $10, $FF