; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GOOMBA, $0D, $18
	.byte OBJ_REDTROOPA, $12, $15
	.byte OBJ_GOOMBA, $29, $18
	.byte OBJ_GOOMBA, $33, $18
	.byte OBJ_GREENTROOPA, $47, $16
	.byte OBJ_REDTROOPA, $49, $10
	.byte OBJ_REDTROOPA, $4F, $0D
	.byte OBJ_GOOMBA, $54, $19
	.byte OBJ_REDPIRANHA, $57, $17
	.byte OBJ_REDTROOPA, $78, $19
	.byte OBJ_REDTROOPA, $7F, $19
	.byte OBJ_REDTROOPA, $81, $19
	.byte $FF
